Support multiple push branches
philips-software/docker-ci-scripts pull request #47
Opened 2020-09-21 19:21 UTC by vmaggioli

2020-09-22 14:01 UTC, JeroenKnoops requested changes
If you want, I can give it a try to add `push-branch`..

2020-09-22 14:01 UTC, JeroenKnoops commented on action.yml
> +  push-branches:
Changing the argument from `push-branch` to `push-branches` will break the API.
Maybe we can add both, and mark `push-branch` deprecated.

2020-09-22 15:11 UTC, JeroenKnoops commented on action.yml
> +  push-branches:
I've gave it a try in https://github.com/philips-software/docker-ci-scripts/commit/524f4cb88f6aee1c84c9d3d06f9a9c439c320b24
Can you include that commit in this PR?

2020-09-22 18:57 UTC, vmaggioli commented
Merged in your commit

2020-09-23 07:18 UTC, JeroenKnoops approved these changes

2020-09-23 07:19 UTC, merged