Attach provenance to image
philips-software/docker-ci-scripts pull request #95
Opened 2022-01-25 14:41 UTC by JeroenKnoops

# Related PR
Please first merge this PR: #94 

# Related Issue
Issue #78

2022-01-25 14:55 UTC, marcofranssen requested changes
Two small improvements in documentation for syntax highlighting.

Just wondering, why don't we use the actions?

https://github.com/sigstore/cosign-installer

IMHO we should leverage the eco-system more as opposed to making fat Docker images with everything preinstalled.

e.g. only do a check if the required tools are there and leave it to the enduser to copy the 2 lines of yaml into the workflow.

Another approach would be to make reusable workflows that combine a bunch of Github actions. 
https://docs.github.com/en/actions/using-workflows/reusing-workflows

This feels very unnatural in the Github actions ecosystem.

2022-01-25 14:55 UTC, marcofranssen commented on README.md
> +```
```suggestion
```yaml
```

2022-01-25 14:55 UTC, marcofranssen commented on README.md
> +```
```suggestion
```yaml
```

2022-01-25 16:17 UTC, JeroenKnoops commented on README.md
> +```
fixed

2022-01-25 16:17 UTC, JeroenKnoops commented on README.md
> +```
Fixed

2022-01-26 08:18 UTC, Brend-Smits approved these changes
Great work, I think this is a good addition in combination with the SLSA provenance feature. 
This makes it easy for novice users to start generating and attesting the provenance of their assets. 
In the end, we can't all be experts about the topic, we need a low barrier to entry(and thus easy) for these building blocks. For experts, this action is likely not enough, which is fine. They can use the already available actions from Cosign or SLSA-Provenance-Action.

2022-01-26 08:18 UTC, Brend-Smits commented on README.md
> +Verify attestation for a certain docker-repo f.e. `jeroenknoops/test-image:latest`:
To people that are not in this line of business, they might not know what they should verify an attestation. 
Can you explain a bit more on why this is needed? In language that the majority of the beginners can understand. Only if we teach people the need for this, they will start using this. 
It would also be good to mention that this verification can be used in later steps in workflows. (e.g. before releasing)

2022-01-26 09:41 UTC, JeroenKnoops commented on README.md
> +Verify attestation for a certain docker-repo f.e. `jeroenknoops/test-image:latest`:
Added more information about that.

2022-01-26 09:49 UTC, Brend-Smits approved these changes

2022-01-26 11:30 UTC, marcofranssen approved these changes

2022-01-26 11:54 UTC, merged